### ISSUE TITLE
Issue using Calcium40 class

### ISSUE THREAD

**Issue by henryfpassagem** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#105]
I am getting the error below. I am not quite sure how to fix it.

![image](https://user-images.githubusercontent.com/68475407/158177032-9434052b-4f7e-4048-bd24-3143939b3bf7.png)

**Comment by nikolasibalic** [comment]
I confirm bug, will fix it now.

**Comment by nikolasibalic** [comment]
@henryfpassagem thank you for reporting this!

There was [one extra empty line](https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/commit/d0f339d06071a8a6a2a60694fb9f6515ba91c8bf#diff-6625b5ca52b1073d9bb22ebe7376c9f8f6b9b60edb90684341a2e4258f225df3) in Ca40 data file, but that was enough to prevent correct Ca instance creation.
This is fixed now in version 3.1.10 that is available on PyPI. Please upgrade the package.
