### ISSUE TITLE
How to calculate angular dependance with external magnetic field?

### ISSUE THREAD

**Issue by DanielYang2017** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#11]
Maybe it can calculate angular dependance with tunable external magnetic field, the expected result is like(From Saffman, RMP, 2010):

![new](https://user-images.githubusercontent.com/30108183/30534632-9a70cb8a-9c91-11e7-96fd-0782adf80e5a.png)

But I didn't find any available example in the document...

**Comment by nikolasibalic** [comment]
@DanielYang2017 Adding magnetic field is not supported at the moment. That's on the list for future extensions.
