### ISSUE TITLE
Usage question: obtaining C6 coefficients between two rydberg `s` states

### ISSUE THREAD

**Issue by Sinestro38** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#110]
Hi! 

Have a quick usage question, how may I obtain the C6 coefficients between 2 Rydberg `s` states for various principal quantum numbers (`n`) on Rb-87?

Thanks!

**Comment by nikolasibalic** [comment]
Hi @Sinestro38 ,

I would suggest you to start by looking at the [examples given here](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/Rydberg_atoms_a_primer_notebook.html#Dispersion-Coefficients), and then adjust them for your needs with the help of documentation.

Best wishes,
Nikola
