### ISSUE TITLE
(ARC 3.2) Wrong HFS data for Na23

### ISSUE THREAD

**Issue by hpaantee** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#116]
When using `getHFSEnergyShift(...)`, the values for the ground state 3S1/2 of Na23 seems to be wrong.
It gives me values of` [-1107.2625    664.3575]`, seemingly in units of MHz, while for other states and elements it always returns in units of Hz.

**Comment by nikolasibalic** [comment]
@hpaantee Thank you for reporting this. Indeed data was saved in units of MHz instead of Hz for this HFS state. I just fixed the bug, and update will be available in next release.

**Comment by hpaantee** [comment]
Thanks! After updating and deleting the `na23_precalculated.db` file in the `.arc-data/` folder of my home directory it works.
