### ISSUE TITLE
'database is locked' for PairStateInteractions

### ISSUE THREAD

**Issue by ranfinkelstein** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#119]
Hi,
When I call PairStateInteractions I get an '[OperationalError: database is locked]'.
All other functionality seems to work fine. 
I am using a Windows machine with Anaconda and Python 3.9.7

Thank you!

**Comment by ranfinkelstein** [comment]
Works on another machine though.

**Comment by nikolasibalic** [comment]
HI @ranfinkelstein 

Most likely program crashed/was terminated before releasing lock on database. There is a small chance that happens.
To solve that just delete all `.db` files in `.arc-data`.   On Linux these are `~/.arc-data/*.db`
