### ISSUE TITLE
Problem with hyperfine state computations in 39 K

### ISSUE THREAD

**Issue by quantockhills** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#128]
I came across a potential bug, where the hyperfine coefficient Ahfs of the ground state of 39 K (n = 4, l = 0, j = 1/2) is given in units of MHz (in 'k39_hfs_data.csv', the value is '230.86' which should instead be '230860000') whereas the standard units (and the ones the other Ahfs coefficients are expressed in) are in Hz. This leads to incorrect calculations of the Zeeman energies for this state (using the breitRabi function), amongst other things.

**Comment by nikolasibalic** [comment]
@quantockhills Thank you for reporting this!

It's fixed and released now as v3.2.6. If you encounter any problems, please let me know!
