### ISSUE TITLE
Query about the tranistion wavelength's calculated by the ARC package.

### ISSUE THREAD

**Issue by nishant-joshi** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#134]
Dear Nikola,
 
I am a Phd student at the Raman Research Institute, Bangalore, India. I have a query about the numbers calculated using the Alkali Rydberg calculator and also the Online Atom calculator.
 
We have a Lithium experiment in our lab.
 
For the purpose of initial benchmarking I was trying to calculate the 2 S_{1/2}->2 P_{3/2} transition wavelength of Lithium7 and Lithium6. This is the D2 transition.
 
I know that 2 S_{1/2}->2 P_{3/2} transition wavelengths of Lithium7 and Lithium6 differ by around 10GHz. Please see figure 1  of the following article: https://journals.aps.org/pra/abstract/10.1103/PhysRevA.75.052508
 
But when I calculate the 2 S_{1/2}->2 P_{3/2} transition wavelengths for Lithium7 and Lithium6 using ARC then I get the same number. I used the following code:

%matplotlib inline           
import matplotlib.pyplot as plt  
import numpy as np               
from IPython.core.display import display, HTML 

atom1 = Lithium6()
atom2=Lithium7()

# Lithium6 2S_{1/2} -> 2P_{3/2} transition...

print("Li6 Excitation 2S_{1/2} -> 2P_{3/2}")
n1 = 2; l1 = 0; j1 = 0.5; #Initial State
n2 = 2; l2 = 1; j2 = 1.5; #Final State
print("lambda = %.3f nm" % (atom1.getTransitionWavelength(n1,l1,j1,n2,l2,j2)*1e9))
print("omega/2pi = %.3f THz" % (atom1.getTransitionFrequency(n1,l1,j1,n2,l2,j2)*1e-12))

# Lithium7 2S_{1/2} -> 2P_{3/2} transition...

print("Li7 Excitation 2S_{1/2} -> 2P_{3/2}")
n1 = 2; l1 = 0; j1 = 0.5; #Initial State
n2 = 2; l2 = 1; j2 = 1.5; #Final State
print("lambda = %.3f nm" % (atom2.getTransitionWavelength(n1,l1,j1,n2,l2,j2)*1e9))
print("omega/2pi = %.3f THz" % (atom2.getTransitionFrequency(n1,l1,j1,n2,l2,j2)*1e-12)

 
I tried to double-check it using the Online Atom calculator but I get the same result.
 
The numbers which ARC gives for Lithium7 are fine but for Lithium6 they are off by 10GHz.
 
This same issue is there in the case of Rubidium 85 and Rubidium 87 as well.
 
Can you please tell me if I am missing something or whether it is the limitation of the ARC package.
 
Nishant
 
Raman Research Institute,
Bangalore,
India.

**Comment by johnny-sa** [comment]
A lot of the transitions are not complete as they have not been implemented or recorded. I would look up the documentation to see where it gets the transition wavelengths from etc.

**Comment by nikolasibalic** [comment]
Hi @nishant-joshi sorry for delay in response.

You can [read in documentation](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/generated/arc.alkali_atom_functions.AlkaliAtom.getEnergy.html#arc.alkali_atom_functions.AlkaliAtom.getEnergy) how energies of the states are calculated.
Key thing for the low lying states, we don't use quantum defects (as usually they don't interpolate as well low lying states as they do the higher lying states). Instead we used NIST data. It's single data set for both isotopes, so for these low-lying transitions you won't see difference between isotopes.

I am closing this issue now. Please feel free to reopen or add comment if you have further questions.
