### ISSUE TITLE
Missing magic wavelength snippet in docs

### ISSUE THREAD

**Issue by galClassiq** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#144]
hi! 
I've been reading the docs for [this function ](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/generated/arc.calculations_atom_single.DynamicPolarizability.plotPolarizability.html?highlight=magic#arc.calculations_atom_single.DynamicPolarizability.plotPolarizability) and noticed the link for the magic wavelength snipped is returning a 404 error. 
is there a working snippet somewhere or is? 

thanks!

**Comment by nikolasibalic** [comment]
Hi Gal!

Thank you for opening this issue. I am fixing it now. But in the meantime you can find example [here](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/ARC_3_0_introduction.html#Calculations-of-dynamic-polarisability-and-magic-wavelengths-for-optical-traps).
