### ISSUE TITLE
Quantum defect for G9/2 states in Caesium return 0

### ISSUE THREAD

**Issue by johnny-sa** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#149]
i.e. 

Caesium().quantumDefect[1][4] = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

I know that these have not been measured in Caesium but at the moment this gives hugely erroneous results such as 

Caesium().getTransitionFrequency(17,3,3.5,17,4,4.5) returns ~43 GHz 
 
compared to

Caesium().getTransitionFrequency(17,3,3.5,17,4,3.5) returns ~34.9 GHz 

giving the G fine structure splitting as >6 GHz!

 would either suggest;

- Use the empirical formula used for higher l states (H, I, etc.) to calculate this or (more easily)
- Use the same quantum defects that have been measured for the G7/2 (similar to how F7/2, F5/2 splittings are 0 at the moment.)

quick fix would be setting Caesium().quantumDefect[1][4] = [0.00703865, -0.049252, 0.01291, 0.0, 0.0, 0.0]

This doesn't appear to be an issue in other species Rb etc. I think that this row was simply omitted by mistake

**Comment by nikolasibalic** [comment]
Thank you for raising this. I've added in the commit above the suggested second solution (set QD for both states to be the same)

**Comment by nikolasibalic** [comment]
Fix released as part of [ARC v3.4.0](https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/releases/tag/v3.4.0)
