### ISSUE TITLE
Intensity Calculation: Is "wa" is a beam radius or beam diameter?

### ISSUE THREAD

**Issue by apoorav-singh** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#157]
I am writing in the context of the function:

[atom.groundStateRamanTransition()](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/_modules/arc/alkali_atom_functions.html#AlkaliAtom.groundStateRamanTransition)

For the Electric field calculation, when Intensity is calculated there is an factor of 2 multiplied to the equation.

`Ia = 2.0 * Pa / (pi * wa**2)`

I have a doubt that,

- Case 1: 
If "wa" aka beam waist is the diameter (or 1/e^2 for gaussian beam) of the beam. Than for area calculation radius is given as '(wa/2)^2' . So one should get factor of 4 not 2 in the numerator.

- Case 2: 
If the "wa" aka beam waist radius is entered no factor should follow. Therefore,

`Ia = Pa / (pi * wa**2)`

If in case I missing something please feel free to correct me.

**Comment by nikolasibalic** [comment]
Hi @jonathanpritchard could you please verify this and reply?

**Comment by jonathanpritchard** [comment]
This is beam radius - the definition of peak intensity for a Gaussian beam is 2P/(pi*w0**2) see https://en.wikipedia.org/wiki/Gaussian_beam for proof
