### ISSUE TITLE
Wigner 6j for non-integer sum triads

### ISSUE THREAD

**Issue by petermao** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#158]
In PR #148, I had left the return value for non-integer sums as `np.nan` because I didn't know any better:

https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/blob/36b86d1a43b3d24f93621ed669926b975494479c/arc/wigner.py#L270-L279

If [Wolfram ](https://mathworld.wolfram.com/Wigner6j-Symbol.html) is right, the proper value to return is `0`.

**Comment by nikolasibalic** [comment]
Released in [ver 3.5.0](https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/releases/tag/v3.5.0)
