### ISSUE TITLE
Breit Rabi isn't outputting the right F and mf states

### ISSUE THREAD

**Issue by VNastya** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#159]
Hi,

I've been reviewing the documentation of the breitRabi function, and it appears there might be an issue with two of its outputs. According to my understanding, this function should output both the energy and also the F and mf states for a given magnetic field:

![image](https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/assets/108177772/67505593-a456-4609-a5c9-d6f990d8178e)
 
While the energy values it outputs agree with previous calculations I have seen it doesn't output the right m and MF states. I checked it for various atoms and atomic states, the result is the same. It's possible that there's an error in the calculation of the quantum numbers, or I might be misunderstanding the documentation. I have attached a code example and the hyperfine structure it generates for potassium 40. It this particular case, the F states should be 9/2 and 7/2. 

Thanks,

Nastya

![image](https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/assets/108177772/7c71cf8e-f2df-478f-82dd-2479501a40f8)

![image](https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/assets/108177772/67c5a7d5-1ab5-4f78-9569-35d6143c32c0)

**Comment by nikolasibalic** [comment]
Fix released in version 3.5.0
