### ISSUE TITLE
pip install not installing binary on Windows

### ISSUE THREAD

**Issue by nikolasibalic** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#16]
It seems pip install under Windows doesn't install binary for Numerov integration. I am looking at the problem that seems to happen during wheel creation/upload process. Error received on Windows is:
``` 
File "arc\alkali_atom_functions.py", line 175, in __init__
    from arc.arc_c_extensions import NumerovWavefunction
ImportError: No module named arc_c_extensions
```

**Comment by nikolasibalic** [comment]
This might be only the problem in incorrect use of Appveyor? I will be able to do more checks on Windows on Friday. If anyone experiences this error under Windows, and has more information (full traceback etc), please let me know. On the machine where it was originally spotted, there was a problem with old installation of Numpy library, that was solved with ```conda update numpy```.

**Comment by dihm** [comment]
Just to offer another datapoint on this, I just upgraded from v1.3 to v2.0.0 on pip. I can import NumerovWavefunction without error. However, I'm not sure the binary installed correctly. v1.3 had a build folder with an actual .lib file. My v2.0.0 pip installation only has the .pyd for the c_extensions.

**Comment by nikolasibalic** [comment]
@dihm Thanks for insight! If you can run this line in Python:

```from arc import * ;atom=Caesium();a1,b1 = atom.radialWavefunction(0,0.5,0.5,atom.getEnergy(15, 0, 0.5)/27.211,atom.alphaC**(1/3.0),2.0*15*(15+15.0), 0.001)```

without errors, everything is fine. If it does produce some errors, please let me know (together with Windows version).

**Comment by nikolasibalic** [comment]
**Status update:** pip installation on Windows seems to work after all. The problems I saw seem not to be related to ARC package itself, but to outdated Python environment on the particular machine.

I will keep this open for a while if someone experiences related issues, until I have time to check on more different installations myself.

**Comment by nikolasibalic** [comment]
No new problems reported. Closing this for now.

**Comment by galwiner** [comment]
hey, 
i'm encountering the same issue on a windows machine. 
i've been having tons of config issues though, so it may just be the mess i made... 


`Traceback (most recent call last):
  File "C:\Users\Gal\Anaconda3\envs\scientific_project1\lib\site-packages\IPython\core\interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-b8684d83140b>", line 1, in <module>
    arc.Rubidium87()
  File "C:\Users\Gal\Anaconda3\envs\scientific_project1\lib\site-packages\arc\alkali_atom_functions.py", line 175, in __init__
    from .arc_c_extensions import NumerovWavefunction
  File "C:\Users\Gal\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\182.4505.26\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: No module named 'arc.arc_c_extensions'`

**Comment by nikolasibalic** [comment]
Hi Gal! @galwiner 

Let me know please which Windows you have (32/64), and which Python version you are using. Did you installed latest version via pip (should be 2.0.4)?

Also, are you running from some special environment (like Spider)? If so, have you tried running vanila code, just by calling 

```
python your_code.py
```

from command line?

**Comment by galwiner** [comment]
hey! 
i'm running 64 bit windows, but it was indeed a config issue. 
after trying to a while, i ran vanila code from the console as you suggested. it ran fine.
i was trying to run from pycharm, and was failing. 
eventually i deleted the pycharm configuration file and created a new conda environment and that fixed the issue. 
thanks!
