### ISSUE TITLE
pull request 155 (approved) did not update `arc.alkali_atom_functions.__arc_data_version__`

### ISSUE THREAD

**Issue by CuriousCesium** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#160]
Hello, 

I just noticed that there was a recent update to `cs_NIST_level_data.ascii`. To use the new values, the corresponding local data file in `~/.arc-data` needs to be updated. I saw that `arc.alkali_atom_functions.setup_data_folder` is designed to update the local data files if there is a mismatch between version numbers stored in `~/.arc-data/version.txt` and in the dunder variable `__arc_data_version__`. Because the pull request that updated `cs_NIST_level_data.ascii` did not update the dunder variable, my team members experienced a problem where users who had used `arc` module before got one value for a Cesium energy level and new users who freshly installed `arc` on their laptops got another value. 

I think `__arc_data_version__` should be incremented from the current value of 10 to 11 and I also wonder what can be enforced to prevent this kind of mistake in the future.

**Comment by nikolasibalic** [comment]
Fixed in 3.4.1. release.
