### ISSUE TITLE
Transition frequency mismatch of Rb87 D2 line

### ISSUE THREAD

**Issue by gabbence95** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#164]
According to [Steck's datasheet](https://steck.us/alkalidata/rubidium87numbers.1.6.pdf), the transition frequency of the D2 line of Rb87 is 384.230**4844685** THz. With ARC I get 384.230**3532225151** THz.

**Comment by nikolasibalic** [comment]
Value in Steck is the best measured result for D1. The ARC uses for low lying state [NIST values](https://physics.nist.gov/cgi-bin/ASD/energy1.pl?de=0&spectrum=Rb+I&submit=Retrieve+Data&units=4&format=0&output=0&page_size=15&multiplet_ordered=0&conf_out=on&term_out=on&level_out=on&unc_out=1&j_out=on&lande_out=on&perc_out=on&biblio=on&temp=) that cover much larger number of energy levels. 80 MHz discrepancy between the two is consistent with uncertanties of the sources. Depending on your purpose, you might find that this absolute difference of the order of 1 in 1000,000 is important for particular atomic calculation, but for most cases the NIST value should be fine. I hope this helps.
