### ISSUE TITLE
Improving accuracy of ground state-Rydberg state transition frequency calculations

### ISSUE THREAD

**Issue by nikolasibalic** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#21]
The [paper Gallagher 2003 used for quantum defects](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.67.052502) for Rb 87 did fittings of D states up to n ~ 37. And they were able to fit measurements using just two quantum defect values (\delta_0 and \delta_2).

I am wondering now if fits were done for larger range of principal quantum numbers, if they would be significantly different? Would these fits have to involve also more terms in fitting function, as it is sometimes used for other alkali metals? By going to n = 84 and n = 97 experiments now are going quite far from the original explored range (see #20).

I have no precise feeling could this account for residual 200 MHz difference between current calculations for n D states in Rb 87 (n~80-100) - if someone has some comments on this, please write!

_Originally posted by @nikolasibalic in https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/issues/20#issuecomment-427035034_

**Comment by kwnminho** [comment]
This paper [Fortágh 2011] (https://journals.aps.org/pra/abstract/10.1103/PhysRevA.83.052515)had done the fitting upto n= 50 - 60, and quantum defects with smaller uncertainty. Rb 87, nS and nD states.

**Comment by nikolasibalic** [comment]
@kwnminho Thank you for reference. Difference in absolute energies of the states between the used quantum defects and quantum defects in Fortágh 2011 are ~ 1 MHz, so quantum defects are not the reason for difference you see.

In fact, I calculated from data in Fortágh 2011 transition frequencies from center of gravity of 5 S_1/2 state to n D_5/2 state, and compared this values from the values obtained from ARC: 

```python
from arc import *

meck_P_3_2_to_nD_5_2_freq = [615.2402660, 616.3411990, 617.2784664, 618.0829639, 618.7786314,
                             619.3842463, 619.9147046, 620.3819464, 620.7956283, 621.1636344,
                             621.4924518, 621.7874500, 622.0531143, 622.2932066, 622.5109082,
                             622.7089185, 622.8895425, 623.2062666, 623.3455461, 623.4738779,
                             623.5923802, 623.7020295, 623.8036883, 623.8981149, 623.9859786,
                             624.0678704, 624.1443264, 624.2827502, 624.4598714, 624.5611995,
                             624.6075890, 624.6514104, 624.7320704
                            ]
meck_P_3_2_to_nD_5_2_n = [19, 20, 21, 22, 23, 
                          24, 25, 26, 27, 28,
                          29, 30, 31, 32, 33,
                          34, 35, 37, 38, 39,
                          40, 41, 42, 43, 44,
                          45, 46, 48, 51, 53,
                          54, 55, 57]

# in THz relative to the center of gravity of 5 S_1/2
meck_ionisation_5_S_1_2 = 1010.0291646-4.271676631815181e-3


# obtain 5_S_1_2_to_5_P_3_2 F=3 transition frequency from center of gravity of 5 S_1/2 state
# from ionisation frequency of 5 P_3_2 F=3 state
meck_5_S_1_2_to_5_P_3_2_freq = meck_ionisation_5_S_1_2 - 625.7942148  # in THz


atom = Rubidium87()

difference = []
for index, n in enumerate(meck_P_3_2_to_nD_5_2_n):
    difference.append(( meck_5_S_1_2_to_5_P_3_2_freq + meck_P_3_2_to_nD_5_2_freq[index]
                          - atom.getTransitionFrequency(5, 0, 0.5, n, 2, 2.5)*1e-12 )*1e6)
    
plt.plot(meck_P_3_2_to_nD_5_2_n, difference, "rs")
plt.title("5 S 1/2 -> n D 5/2")
plt.xlabel("Principal quantum number")
plt.ylabel("Difference in energy (MHz)")
plt.show()
```

![comparison](https://user-images.githubusercontent.com/24477754/46610137-27a47180-cb0a-11e8-9ab3-b14efea6f216.png)

@kwnminho As you can see, differences between ARC values and values in that paper are of the order of MHz. If you see difference of order ~ 100 MHz between your measurements and current ARC values, that implies there is difference between your measurements and Fortágh 2011. I would then strongly suspect that it might be just some factor in data analysis (like offset of 193 MHz between P_3/2 F=3 state from center of gravity of P_3/2 line). Can you confirm maybe this?

**Comment by kwnminho** [comment]
Hi @nikolasibalic , I have also done calculations using quantum defects from Fortagh paper and saw virtually no difference, and suspecting I might have missed some factor in the analysis as you said. 

I will update once I find something. Thanks for cross-checking!

**Comment by nikolasibalic** [comment]
It seems that after correcting for hyperfine offset of the ground state (#20) ARC is reproducing correctly the transition frequencies from the ground state, and other reported discrepancies  seem to be experimental. I am closing the issue now. @kwnminho Please comment if you find any new evidence.
