### ISSUE TITLE
ARC for alkaline earth 

### ISSUE THREAD

**Issue by galwiner** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#33]
Hi Nikola, 

I'm bringing this issue on behalf of my friend and co-worker Ran Finkelstein. 

See below: 

______________________________________

Dear Nikola,

Thank you so much for the wonderful  ARC  package.

I wanted to carry out a calculation for transitions in Rydberg states with Sr atoms, which are Alkaline-earth atoms.

Do you think it would be possible to get literature values of these in ARC? Or other, more elaborate, calculations?

 

Thank you,

Ran Finkelstein

**Comment by nikolasibalic** [comment]
Will be possible very soon, working on that.

**Comment by galwiner** [comment]
Amazing!
Thanks!

**Comment by nikolasibalic** [comment]
Hi @galwiner ,

You can test new functionality now by calling
```python
from arc import *
from arc.beta import *
```

Note that the second line is necessary to access beta features that we are currently testing (Alkaline Earth support). I will send you by email draft notebook with some examples that will be included in documentation at later stage.
