### ISSUE TITLE
refractive-index-data missing after update to arc 2.2.0

### ISSUE THREAD

**Issue by galwiner** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#36]
Hi! 

We've updated to the latest ARC and we now cannot import the library. 

We get the following error message:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-f7c4c431d663> in <module>
----> 1 from arc import *
      2 #from arc.beta import *  # This is necessary for running this notebook before official release of ARC 3.0.0

~\Anaconda3\envs\physics\lib\site-packages\arc\__init__.py in <module>
      4 from __future__ import division, print_function, absolute_import
      5 
----> 6 from .alkali_atom_data import *
      7 from .calculations_atom_single import *
      8 from .calculations_atom_pairstate import *

~\Anaconda3\envs\physics\lib\site-packages\arc\alkali_atom_data.py in <module>
     87 from __future__ import division, print_function, absolute_import
     88 
---> 89 from .alkali_atom_functions import *
     90 
     91 from scipy.constants import Rydberg as C_Rydberg

~\Anaconda3\envs\physics\lib\site-packages\arc\alkali_atom_functions.py in <module>
   2487 
   2488 
-> 2489 setup_data_folder()

~\Anaconda3\envs\physics\lib\site-packages\arc\alkali_atom_functions.py in setup_data_folder()
     93             os.makedirs(refractiveIndexData)
     94 
---> 95         for fn in os.listdir(dataFolder):
     96             if os.path.isfile(os.path.join(dataFolder, fn)):
     97                 shutil.copy(os.path.join(dataFolder, fn), refractiveIndexData)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\fewin\\Anaconda3\\envs\\physics\\lib\\site-packages\\arc\\data\\refractive_index_data'

**Comment by nikolasibalic** [comment]
I've added also second correction just to make sure that data is copied. New packages are currently being compiled. You can test in ~ 20 - 25 min if everything is fine now. Sorry for this, apparently * in distribution script does not include subfolders so I had to added it explicitly  2ad4bd9  .
