### ISSUE TITLE
Wigner3j evaluate to nan for Wigner3j(50,1/2,49.5,50,-1/2,-49.5)

### ISSUE THREAD

**Issue by zzpwahaha** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#39]
In the calculation of Zeeman energy shift, the result is inf for ```atom.getZeemanEnergyShift( 50, 49.5, 49.5,0)```. Mainly because the ```CG(50,50,1/2,-1/2,49.5,49.5)``` spit out nan which is the result of Wigner3J.

Maybe try to lower the bound in line 60 in Winger3J
 ```if (j1 > 50 or j2 > 50 or j3 > 50 or m1 > 50 or m2 > 50 or m3 > 50):```

**Comment by nikolasibalic** [comment]
@zzpwahaha  Many thanks for reporting this, finding core cause, and suggesting solution.
I lowered bound from 50 to 40 now, as suggested, and indeed now it works. New version (2.2.12) has just finished building and can be downloaded with pip.
