### ISSUE TITLE
dyn.getPolarizability(850e-9,units='SI',accountForStateLifetime=True)

### ISSUE THREAD

**Issue by zzpwahaha** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#55]
Hi
In the DynamicPolarizability module, the DynamicPolarizability.lifetime is initilized with a null list and does not have attribute length. So in the code`def getPolarizability`

> if (accountForStateLifetime and self.lifetimes.length == 0):
            for state in self.basis:
                self.lifetimes.append(self.atom.getStateLifetime(state[0],
                                                                 state[1],
                                                                 state[2],
                                                                 s=self.s))

there is an error the first line

**Comment by nikolasibalic** [comment]
Hi @zzpwahaha ,

Thank you for submitting this report. However I think this is fine. Here is why:

Before ```DynamicPolarizability``` calculation methods like ```getPolarizability``` are called, one has to define basis in which he or she wants to work. ```defineBasis``` would define which states should be included in calculations, and also set self.lifetimes = [] .

So later on when one calls ```getPolarizability``` everything should work fine.

Is this fine with you or you run in some other problems?

**Comment by zzpwahaha** [comment]
Thanks for your reply. I think the issue is not the initialization of self.lifetime, but the fact that a list object in Python does not have an attribute length. May be substitute it for self.lifetimes.__len__().
Because I got an ERROR saying exactly the same thing as I run the getPolarizability function with the accountForStateLifetime parameter set to be True.

**Comment by nikolasibalic** [comment]
Thank you for submitting this bug @zzpwahaha !

I've just corrected it and new version (3.0.6) has a fix.
