### ISSUE TITLE
Apparent Ca40 spectroscopic data issue

### ISSUE THREAD

**Issue by rbrown137** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#57]
Thank you for working to extend this useful tool to divalent atoms.   When attempting to plot the levels of Ca40 using calc.makeLevels(4,50,0,1,sList=[0]), I do not see the ground state that I would expect at -6.11 eV (https://physics.nist.gov/PhysRefData/Handbook/Tables/calciumtable5.htm)  accordingly the $4s^2$    $^0S_1 \rightarrow$ $4s4p$ ^1P_1$ transition at 422.7 nm shows up as 6412.3 nm in the attached plot.  In case I incorrectly specified the lowest principal quantum number, I have tried calc.makeLevels(1,50,0,1,sList=[0]) and got the same plot. 

![Ca40_S_P_singletstates](https://user-images.githubusercontent.com/68356788/104133803-da9c4f00-5353-11eb-8f35-91684186a64e.png)

Side note: a potentially relevant reference for Ca atomic data: _Oscillator strengths of the 4s4p 1,3P1 → 4snd 1,3D2 transitions
of neutral calcium_ DOI: 10.1140/epjd/e2008-00193-0

**Comment by nikolasibalic** [comment]
Thank you for reporting this error. We missed to insert data for low-lying Ca states. I will correct this tomorrow (Monday) and update here on status once update is pushed to repository.

**Comment by nikolasibalic** [comment]
@rbrown This should be resolved in ARC 3.0.8 available now in PyPI. Please reopen issue if problems persist.

In principle divalent data is still scarce, and we need to expand it as it becomes available. Thank you for sharing that reference, and please do share any other relevant data too.

**Comment by nikolasibalic** [comment]
Thank you Roger,

At the moment we keep references in documentation, citing them in comments depending where the values are used (documentation is generated from code comments so everything is on one place). Mostly it's *_data.py files and /data folder. If you have specific update there, you can submit pull request.

Alternatively, if you just have a list of various references that might come useful at different places, textual contribution in a form of open issue it is great. I will go through them then.

If you need any assistance, I am here to help, Many thanks for contribution!
