### ISSUE TITLE
energy unit options in figures

### ISSUE THREAD

**Issue by petermao** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#65]
on my own copy (installed via pip), I tweaked LevelPlot's and StarkMap's plotting routines to plot in 'GHz', '1/cm' or 'eV'.  I wanted to be able to see those figures in the same units.

If desired, I can contribute it to you code via a branch or fork.  The mods to your code were pretty minor.

**Comment by nikolasibalic** [comment]
@petermao Access should work now, I sent invitation.

**Comment by petermao** [comment]
pushed!  I didn't realize I could make a pull request from a local branch.

**Comment by petermao** [comment]
@nikolasibalic: I'm glad to be of help.  It's a great package you've put together here.

btw -- the python notebooks will crash in some places.  they'll need global replace of "units=2" with "units='ghz'" at a minimum.

**Comment by nikolasibalic** [comment]
This implementation is available now via pip as version 3.0.12.
