### ISSUE TITLE
bug in LevelPlot x-axis label

### ISSUE THREAD

**Issue by petermao** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#69]
In a level plot not showing S, the labels on the x-axis come out incorrectly.  I should see P, D, F, but the labels are cycled left (D in P's place, F in D's place, no label under F).

```
import arc

levels = arc.LevelPlot(arc.Cesium())
levels.makeLevels(99,101,1,3)
levels.drawLevels(units='ghz')
levels.showPlot()
```

(running 3.0.12)

**Comment by nikolasibalic** [comment]
Many thanks for reporting this. It's fixed now and should be working in version 3.0.14.
