### ISSUE TITLE
SI prefixes for physical quantities

### ISSUE THREAD

**Issue by petermao** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#71]
Wavelengths and energies in LevelPlots (and perhaps elsewhere) are reported in fixed units (nm, GHz, eV, cm-1).  I wrote a short function to format these numbers with their SI prefixes.

Shall I push the branch ("si_prefix", locally) for review?

two known issues:
1. \mu is not formatting properly
2. this is not turned off for cm-1, which is contrary to tradition.

**Comment by nikolasibalic** [comment]
Yes please. I have just opened "si_prefix" branch.

Many thanks, excellent idea to add this!

**Comment by nikolasibalic** [comment]
I remember now that in web_functionality.py (for [Atom calculator online](https://atomcalc.jqc.org.uk)) we had one function that might be partially doing similar thing, but it was never used in the main ARC plotting codes:

https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/blob/d16561042fed004be5dcefc7076b2718bf650aa5/arc/web_functionality.py#L66-L86

In any case, I can try mixing/merging/expanding the two ideas if needed, it is very useful if you have written already integration into the LevelPlots!

**Comment by petermao** [comment]
ok, pushed.  Mine is not a perfect implementation (as mentioned above).  Incorporate what you like of it.

**Comment by nikolasibalic** [comment]
Dear @petermao 

Many thanks for your contribution. It took me some time to get round to do some slight reorganization, but now it has been release together with host of improvements contributed over the last 6 months or so, in new version 3.1.0

Best wishes,
Nikola
