### ISSUE TITLE
Would you like to tell me which eigenvalue is what I need when I diagonalize the matrix? (stark map)

### ISSUE THREAD

**Issue by linxiaodong-lom** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#77]
Hi, Sorry to bother you. I have some problems when I diagonalize the matrix of the Hamiltonian. When I calculate the stark shift , I don't know which eigenvalue is what I need. When the electric field is small, I can choose the eigenvalue which is the closest to the energy without field. But when the field is large, It doesn't work.  Would you like to tell me how do you choose the eigenvalue?  Thanks a lot!

**Comment by nikolasibalic** [comment]
Hi @linxiaodong-lom 

Does the following code example helps? It shows you

- how to get for each eField value all eigenvectors and their composition
- how to select the eigenstate with largest contribution of the initial state
- how to select eigenstate that has largest overlap with the previous state in order to find adiabatically connected states as you swipe E field. Note that it is important here to keep eField step sufficiently small: if the state crossing is happening over some deltaE you want to step with step sufficiently smaller than deltaE that you track correctly which state adiabatically converts to what)

```python
from arc import *

calc = StarkMap(Rubidium())
calc.defineBasis(50, 0, 1/2, 1/2, 45, 55, 20, Bz=0, progressOutput=True, debugOutput=False, s=0.5)
eFieldList = np.linspace(00.,6000,600)
calc.diagonalise(eFieldList)

calc.plotLevelDiagram(progressOutput=True,units="GHz",highlightState = True)

stateEnergy1 = []
stateEnergy2 = []

initalState = np.zeros(len(calc.basisStates))  # see Case 2 
initalState[calc.indexOfCoupledState] = 1
print(calc.basisStates[calc.indexOfCoupledState])

for eField in eFieldList:
    m = calc.mat1 + calc.mat2 * eField
    ev,egvector = eigh(m)
    
    # To get contributions to each eigen state in basis
    # stateContributions  = egvector[:, stateIndex]
    # stateBasis = self.basis
    
    # Case 1: find state with maximal contribution of the initial state
    
    maxOverlap = 0  # overlap with initial state - pure basis state
    eigenvectorIndex = 0
    for i in range(len(ev)):
        if ( abs(egvector[calc.indexOfCoupledState, i])**2 > maxOverlap ):
            maxOverlap = abs( egvector[calc.indexOfCoupledState, i] )**2
            eigenvectorIndex = i
    
    stateEnergy1.append(ev[eigenvectorIndex])
    
    # Case 2: find state that has largest overlap to the selected state for 
    # previous value of eField, starting with the initial state for zero field
    # i.e. it is adiabatically connected to the initial state
    
    maxOverlap = 0  # overlap with previous selected state
    eigenvectorIndex = 0
    for i in range(len(ev)):
        if ( abs(np.vdot(egvector[:, i], initalState)) > maxOverlap ):
            maxOverlap = abs(np.vdot(egvector[:, i], initalState))
            eigenvectorIndex = i

    initalState = egvector[:, eigenvectorIndex]  # reference point for search of closest state for higher eField in next step
    
    stateEnergy2.append(ev[eigenvectorIndex])

calc.ax.plot(eFieldList/100, stateEnergy1, "r:")
calc.ax.plot(eFieldList/100, stateEnergy2, "b:")
calc.ax.set_ylim(-1540,-1400)
calc.fig.savefig("test.png")
calc.showPlot(interactive = True)

```
![test](https://user-images.githubusercontent.com/24477754/129354037-7c652ccf-4bb0-44b4-b8e4-6f8c1ccfbf44.png)


Does this resolve your problem?

**Comment by nikolasibalic** [comment]
There is also possibly useful example of accessing `StarkMap` results to build your own calculations on top of it in [Documentation > 
Calculation of dipole matrix elements between states in static electric field](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/_static/Rydberg_atoms_a_primer.html#Calculation-of-dipole-matrix-elements-between-states-in-static-electric-field )

**Comment by linxiaodong-lom** [comment]
Thank you very much! That helps me a lot!
