### ISSUE TITLE
\ell > 4, states in Rb

### ISSUE THREAD

**Issue by rbrown137** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#80]
Hello,
I am interested in refined coverage of ARC to higher, \ell > 4, states.  
For 85Rb, \ell=4, g states there are 4 references that I am aware of: (DOI: 10.1103/PhysRevA.74.054502, 10.1103/PhysRevA.74.062712, Thesis: L. A. M. Johnson, Precision laser spectroscopy of rubidium with a Frequency Comb(University of Leeds, 2011), 10.1103/PhysRevA.102.062817).  To one significant digit these references agree, \delta_g= 0.004.

For  \ell > 4:  \delta_\ell=\delta_g*(4/\ell/)^5  ( expression from https://journals.aps.org/pra/abstract/10.1103/PhysRevA.20.2251 and https://journals.aps.org/pra/abstract/10.1103/PhysRevA.74.062712 )
Using this expression, \delta_h~ 0.0013 (\delta_h = 0.0015 was experimentally determined on pg 147 of LAM Jonhson’s thesis, in decent agreement) and \delta_i~ 0.00053.  In general I would be interested in refined g to h and h to I state intervals as well as dipole coupling matrix elements.  

I can look into Cs \delta_g if you are interested in pursuing this.  
Thanks for your consideration,
Roger

**Comment by nikolasibalic** [comment]
Hello Roger @rbrown137 

Thank you very much for raising this. I am always interested in additional and improved data values!

I know that currently we have for Rb85 and Rb 87 respectively these values for g states:

https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/blob/ddef0902ba5ea5900e868eaeae700b07332388f7/arc/alkali_atom_data.py#L343

https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/blob/ddef0902ba5ea5900e868eaeae700b07332388f7/arc/alkali_atom_data.py#L468

Which agrees with  \delta_g= 0.004 that you refered.
For higher states we indeed have not entered values, so I will follow up the references you provided and update this weekend.

And yes, if you have data reference for Cs let me know.
Improving values is in the interest of the whole community, so many thanks for taking time to reach out!

Once the update is done this weekend, I will write here!
Nikola

**Comment by nikolasibalic** [comment]
Dear @rbrown137 ,

I have incorporated this for \ell > 4. Now for all elements for which \delta_g is defined this will be calculated acccording to that scaling (see 7d01ae39e851795729d2194d24ab52c214564bb9 ).

This has been released now as version 3.1.0, together with host of improvements accumulated over the last 6 months.

Best wishes,
Nikola
