### ISSUE TITLE
Numpy ValueError: cannot reshape array of size 0 into shape (338136,7) while importing atoms data

### ISSUE THREAD

**Issue by Vanimiaou** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#84]
Hello,

I have been using ARC and it was working fine until today it suddenly crashes. When I tried to import the atoms data using Caesium() or StarkMap(Cesium()) using the following code:

```python
import arc
import numpy as np
from arc import *
from arc.beta import *  

atom=Caesium()
```

then the following error came out:

```python
Traceback (most recent call last):

  File "C:\Users\Admin\Desktop\Projects\StarkMap\TDM_Efield_42F42G.py", line 16, in <module>
    atom=Caesium()

  File "C:\Users\Admin\anaconda3\lib\site-packages\arc\alkali_atom_functions.py", line 212, in __init__
    data = np.load(os.path.join(self.dataFolder,

  File "C:\Users\Admin\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 440, in load
    return format.read_array(fid, allow_pickle=allow_pickle,

  File "C:\Users\Admin\anaconda3\lib\site-packages\numpy\lib\format.py", line 783, in read_array
    array.shape = shape

ValueError: cannot reshape array of size 0 into shape (338136,7)
```

I have already tried to reinstall Numpy, ARC and even Anaconda but it didn't fix the issue. Can someone help me with it?

**Comment by nikolasibalic** [comment]
Hi @Vanimiaou 

I never saw this error. My guess is that process was interrupted in the middle of the cache writing and that made some file in the cache. I would suggest to delete temporary ARC cache (this has not been refreshed if you did reinstallation). You can find the cache as hidden folder called .arc-data in C:\Users\Admin\  (or equivalent for username you use) 

Once the cache folder is deleted try running
```python
from arc import *
atom = Caesium()
```
Note that you don't need to use `from arc.beta import *` (this was just for temporary beta version), nor do you need `import arc` if you are already using `from arc import *`.

Can you let me know if this resolves your problem?
If it doesn't please let me know operating system and Python version you are using and I will try to recreate problem.

Many thanks,
Nikola

**Comment by Vanimiaou** [comment]
Dear Nikola,

Thank you very much for your help, Delete catch folder helped! It works normally now.  I also clear out the unnecessary line as you suggested. Thanks a lot I wish you a nice week !

**Comment by Vanimiaou** [comment]
Hi Nikola, can I ask another thing,

I am using getDipoleMatrixElement() and it works with most values, but it gave out an error for some coupling (not the Value error because the coupling is forbidden or anything). For example, if I try Cesium:

```
from arc import *
atom=Caesium()
atom.getDipoleMatrixElement(35,23,23.5,3.5,41,40,40.5,3.5,0)
```

the error came out as

```
Traceback (most recent call last):

  File "<ipython-input-123-706797bef1c5>", line 3, in <module>
    atom.getDipoleMatrixElement(35,23,23.5,3.5,41,40,40.5,3.5,0)

  File "C:\Users\Admin\anaconda3\lib\site-packages\arc\alkali_atom_functions.py", line 1080, in getDipoleMatrixElement
    Wigner3j(j1, 1, j2, -mj1, -q, mj2) *\

  File "C:\Users\Admin\anaconda3\lib\site-packages\arc\wigner.py", line 61, in Wigner3j
    return float(sympyEvaluate(Wigner3j_sympy(j1, j2, j3, m1, m2, m3).doit()))

AttributeError: 'int' object has no attribute 'doit'
```

I do not know why for these quantum numbers particularly, python recognizes the Wigner3j as an integer and how you solve it. Can you help me with it and please let me know if you would like this comment on a separate thread. Thank you very much!

**Comment by nikolasibalic** [comment]
Hi @Vanimiaou 

You are requesting dipole coupling between l_1 = 23 and l_2 = 40. However dipole selection rules limit |l_1-l_2| <= 1. In other words dme would be 0, but instead ARC returns error when you request non-physical value.
If you try with l = 22 you will get because of this `6j-Symbol is not triangular!` error. Now why you don't get that error also for l_1=23 I am not sure. But it seems that you are definitely requesting dipole coupling between states that are not dipole coupled.

Do you agree with this?

**Comment by Vanimiaou** [comment]
Hi Nikola! 

I agree with you, I was running a loop with different quantum number to take account of all the possible couplings between the admixed states, and already raised a ValueError exception for the case where it doesn't satisfy the triangular inequality. 

I didn't check the coupling precisely whether it was forbidden, it was just that it gave an AttributeError instead of a ValueError, so I wondered if I should raise an exception for that too.

thanks !

**Comment by nikolasibalic** [comment]
Yes, I am not sure why it raises AttributeError instead of ValueError, but I don't have time to further look into that at the moment. However, it's good that it stops! :)
