### ISSUE TITLE
StarkMap.getState returns energy in wrong energy unit?

### ISSUE THREAD

**Issue by Dobrzyniecki** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#85]
According to the documentation, StarkMap.getState should return the state's energy in eV (just like the AlkaliAtom.getEnergy function). However, instead it returns the energy in units equal to about 0.000124 eV. 

For example, for the Caesium() state [n=18, l=1, j=1.5, mj=0.5], atom.getEnergy returns a value of "-0.06525808794181294". StarkMap.getState, for the same quantum numbers and zero energy field, returns a value of "-526.3986309533904". 

The culprit seems to be this line in the definition of StarkMap.getState: 
https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/blob/ddef0902ba5ea5900e868eaeae700b07332388f7/arc/calculations_atom_single.py#L1394
As far as I can tell, ev[eigenvectorIndex] is the energy in h*GHz, which then for some reason gets multiplied by 0.03336.

**Comment by nikolasibalic** [comment]
Hi @Dobrzyniecki ,

Many thanks for reporting this bug and identifying source and solution. This has been fixed in release 3.1.0.

Best wishes,
Nikola
