### ISSUE TITLE
Potassium-39 bug

### ISSUE THREAD

**Issue by chrigro** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#92]
Hi Nikola,

I stumbled upon a bug playing with ARC today. Happens immediately upon creation of a "Potassium39" Atom instance with default parameters. Seems there is a problem with `AlkaliAtom._readLiteratureValues()`, which throws: `ValueError: invalid literal for int() with base 10: '4;0;0.5;4;1;0.5;4.098;table V;1;0.001;Physical Review A'`. Going back in the git history, I think this has been introduced between the commits 7d01ae3 (works) and 287853c (crashes).

All the best!
Christian

**Comment by manuelmorgado** [comment]
Yes, I got a similar error for Potassium() Potassium39() and Potassium40() 

`~/anaconda3/envs/q-env/lib/python3.8/site-packages/arc/alkali_atom_functions.py in __init__(self, preferQuantumDefects, cpp_numerov)
    310 
    311         # read Literature values for dipole matrix elements
--> 312         self._readLiteratureValues()
    313         self._readHFSdata()
    314 

~/anaconda3/envs/q-env/lib/python3.8/site-packages/arc/alkali_atom_functions.py in _readLiteratureValues(self)
   1747         # might have been updated in the meantime
   1748         c = self.conn.cursor()
-> 1749         c.execute('''DROP TABLE IF EXISTS literatureDME''')
   1750         c.execute('''SELECT COUNT(*) FROM sqlite_master
   1751                         WHERE type='table' AND name='literatureDME';''')

OperationalError: database is locked`

**Comment by nikolasibalic** [comment]
Thank you for reporting this, and I apologize for this error.

I will fix it this Friday (26.11.2021) evening, have to finish before that some other work. Until then you can try working with old version (might be needed to delete .arc-data hidden folder in case the error lead to corruption of database).

**Comment by nikolasibalic** [comment]
Hi Christian @chrigro  and Manuel @manuelmorgado ,

Version 3.1.4 of ARC fixes formatting of .csv file and is available now on PyPI. We switched to different library for parsing this .csv files, so now quotation marks were needed around strings (5af105621a91f1f1cb5f4278d85820db34cf0ca7). By omission, this has not been updated for Potassium data file. New version will rewrite local cache (.arc_data version is now 9), so in case somehow the crash corrupted existing data store, this should be resolved.

Many thanks for your report,
All the best!
Nikola
